name: IceIsland
description: A powerful core for SkyBlock servers
author: end_shop.id
website: twitter.com/GiantQuartz
main: room17\SkyBlock\SkyBlock
version: 1.0.0
api: 3.0.0

permissions:
  skyblock.interaction:
    description: Allows players to interact with an island regardless of whether they belong to it
    default: op